# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - "1.0"
  - "1.1"
  - "1.2"
  - "1.3"  
  - nightly
matrix:
  allow_failures:
    - julia: nightly
addons:
  apt:
    packages: ['libquadmath0', 'libgomp1', 'libopenblas-dev', 'libfftw3-dev', 'libmpfr-dev']
  homebrew:
    packages: ['gcc@8', 'fftw', 'mpfr']
    update: true

notifications:
  email: false
codecov: true

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("MyPackage"); Pkg.test("MyPackage"; coverage=true)'
